### ISSUE TITLE
Adv Training feature for the new M+ Website Integration

### ISSUE THREAD

**Issue by Teleena** [Icecrown-Community/Icecrown-Precious-Bot-Public#76]
Title. Trainee advertisers will need some way to practice with the new website-oriented M+. Can we have a training category baked in, or something to that effect?

**Comment by iElsha** [comment]
1. Will be on a test discord, different than leaders & member one.
2. Will be the exact replica of the bot

Scoped to 2 hours for me & 2 hours for Tueri

**Comment by iElsha** [comment]
## Tasks
- [x] @Tueri duplicate the server (non linked) and put the correct channel, roles, emojis there
- [x] @iElsha integrate it on the server
- [ ] @Icecrown-Community/icc-member-s-website-developers integrate it on website?

**Comment by iElsha** [comment]
@Tueri see
https://discord.com/channels/755267851689918477/815699868601024543/862775459996893235

**Comment by Tueri** [comment]
> ## Tasks
> * [x]  @Tueri duplicate the server (non linked) and put the correct channel, roles, emojis there
<https://discord.gg/sAWn4CeN83>

Server templated, roles and permissions auto-copied, added bot emoji and cleaned the rest of the channels, should be ready for use.

**Comment by Dejnaa** [comment]
@Teleena is this live? :)

**Comment by iElsha** [comment]
No we are waiting for website implementation then it goes live
