### ISSUE TITLE
[Features] Priority Claim on boosts

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/Icecrown-Precious-Bot-Public#79]
## Feature
Allow specific roles to claim specific boost types in priority over other members.

## Use case
VIP boosters for instance, RBG

## Tasks
- [ ] Set up Firestore collection (activity: array of roles (=team), timer of priority in minutes)
- [ ] Fetch configuration & create interfaces
- [ ] Set up process in BaseRun
- [ ] Test
- [ ] Write tests

**Comment by Tueri** [comment]
This may need to apply to both single boosters and teams.

**Comment by iElsha** [comment]
Fyne, can you let me know of the importance of this feature for us please

**Comment by FyneIcc** [comment]
0, RBG is pretty much dead.

**Comment by iElsha** [comment]
@FyneIcc closing, reopen if we need it one day
