### ISSUE TITLE
[Feature] Inclusive wording

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/Icecrown-Precious-Bot-Public#80]
## Feature

As part of continuous improvement, update messages to include both females and males members/customers by either:
- Using "he/she"
- Using "They"

## Task
- [ ] @iElsha gives strings to Tueri
- [ ] @Tueri makes the changes
- [ ] @iElsha update in code
